# Generated by Django 5.2.17 on 2026-08-14 20:54

import apps.products.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_cover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_cover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_cover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_age', models.PositiveSmallIntegerField(default=100)),
                ('currency', models.CharField(default=apps.products.models.default_currency, max_length=3)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='RatingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_band_min', models.PositiveSmallIntegerField()),
                ('age_band_max', models.PositiveSmallIntegerField()),
                ('rate_per_1000_cover', models.DecimalField(decimal_places=4, max_digits=6)),
                ('loading_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('min_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_rules', to='products.producttype')),
            ],
            options={
                'ordering': ('product', 'age_band_min', '-valid_from'),
                'constraints': [models.CheckConstraint(condition=models.Q(('age_band_min__lte', models.F('age_band_max'))), name='rating_age_band_min_lte_max')],
            },
        ),
    ]
