# Generated by Django 5.2.17 on 2026-08-14 21:03

import apps.policies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_seed_rating_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_reference', models.CharField(default=apps.policies.models.generate_quote_reference, editable=False, max_length=32, unique=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('state', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='new', max_length=20)),
                ('rated_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('quote_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='products.producttype')),
                ('rating_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ratingrule')),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PolicyStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(blank=True, max_length=20, null=True)),
                ('to_state', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('api', 'API'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='policies.policy')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['customer', 'state'], name='policies_po_custome_b89ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['state'], name='policies_po_state_42a0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['created_at'], name='policies_po_created_23231a_idx'),
        ),
        migrations.AddIndex(
            model_name='policystatetransition',
            index=models.Index(fields=['policy', 'created_at'], name='policies_po_policy__72164c_idx'),
        ),
    ]
